added all necessary functions
stino-x/check-list pull request #2
Opened 2023-05-14 01:01 UTC by stino-x

add, delete, edit, refresh(bonus)

2023-05-14 01:21 UTC, franclobo reviewed
Hi @stino-x, 

![terminator](https://github.com/stino-x/check-list/assets/58642949/0bc36dc4-8c99-42ec-994b-22e9e0cb5a02)

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that doesn't have a descriptive PR, please 🙏🏽 add a descriptive summary of the changes in the current branch.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-05-14 01:33 UTC, AnselemOdims requested changes
### Hi @stino-x , 
You have been doing a tremendous job so far :ok_hand:
There are some issues that you still need to work on to go to the next project but you are almost there!

## To Highlight 🎉
PR has a title and summary. :heavy_check_mark:
No linter errors :heavy_check_mark:

## Required Changes ♻️
- [ ] Please also check inline comments under the review

## Optional suggestions
_Comments with the [OPTIONAL] prefix are not a must to implement however, It's strongly recommended to work on them as they can make your code better._

## Happy coding!👏👏👏

#### Please leave any questions or comments in the PR if you have any doubts or unclarity! You can tag me using @AnselemOdims for a quicker response

**_Note: Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-05-14 01:33 UTC, AnselemOdims commented on src/index.js
> +// };
- [ ] Please kindly remove all commented code from your codebase as it does not follow best practices and corrupts the codebase.

2023-05-14 01:33 UTC, AnselemOdims commented on src/index.js
> +// saveTaskstoLocalStorage(); // AddToScreen();
- [ ] Please kindly remove all commented code from your codebase as it does not follow best practices and corrupts the codebase.

2023-05-14 01:54 UTC, AnselemOdims requested changes
### Hi, 
Good job implementing some of the changes requested by the previous reviewer.

## Required Changes ♻️
- [ ] Please also check inline comments under the review

## Optional suggestions
_Comments with the [OPTIONAL] prefix are not a must to implement however, It's strongly recommended to work on them as they can make your code better._

## Happy coding!👏👏👏

#### Please leave any questions or comments in the PR if you have any doubts or unclarity! You can tag me using @AnselemOdims for a quicker response

**_Note: Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-05-14 01:54 UTC, AnselemOdims commented on src/index.js
> +// import DeleteTask from './Modules/Delete.js';
- [ ] As pointed out earlier, you should remove all commented code in all your codebase but there are still some comments

2023-05-14 01:54 UTC, AnselemOdims commented on src/index.js
> +// import { AddtoLocalStorage, saveTaskstoLocalStorage } from './Modules/AddtoLocalStorage.js';
- [ ] Kindly remove this too

2023-05-14 01:54 UTC, AnselemOdims commented on src/index.js
> +    // trashIcon.addEventListener('click', deLete); // event listener
- [ ] Kindly remove this too

2023-05-14 01:54 UTC, AnselemOdims commented on src/index.js
> +    // const taskIndex = Array.from(listItem.parentNode.children).indexOf(listItem) - 1;
- [ ] Kindly remove this too

2023-05-14 01:54 UTC, AnselemOdims commented on src/index.js
> +    // editTask(newDescription, index);
- [ ] Kindly remove this too

2023-05-14 02:15 UTC, AnselemOdims approved these changes
### Hi  @stino-x 🙋‍♀️, 
Good job in making the required changes 👏 

# STATUS APPROVED ✔
Your project is complete!  There is nothing else to say other than... it's time to merge it 🔗 🚢 
Congratulations! 🎉 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers 🥂  and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Use the tag @AnselemOdims for a quicker reply


**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-14 16:11 UTC, brainconnect93 approved these changes
## Status: Approved :heavy_check_mark:

Hi @stino-x, 👋 👋  

Your project is complete! Great job for following the project requirement🥇. There is nothing else to say other than... it's time to merge it 🍾🚢 :shipit: . Congratulations!  🎉💯🌟 


<img src="https://user-images.githubusercontent.com/85113567/184604589-430cf4bc-1d2e-4603-976a-7a48a899ea35.gif" width="600px" height="300px">

### To Highlight :1st_place_medal: 

- Descriptive Pull Request title & summary. ✔️  
- Add and Remove functionality works Perfectly ✔️ 
- Edit Task functionality works fine ✔️ 
- Good use of GitHub flow ✔️ 

## Optional changes

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers..Happy coding!..and keep soaring higher! 💻 🍷 🚀 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @brainconnect93 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 2 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2024-04-05 19:26 UTC, merged